project:
  type: website

website:
  title: "stigmaRverse"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://stigmarverse.github.io/stigmaR/
        text: "R Package"
      - href: https://stigmarverse.github.io/stigmaRdata/
        text: "Data Processing"
      - href: https://stigmarverse.github.io/stigmaRdata/
        text: "Web App"
      - href: https://stigmarverse.github.io/stigmaRdata/
        text: "News"
      - href: https://stigmarverse.github.io/stigmaRdata/
        text: "Tutorial"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



